### ISSUE TITLE
ESX Integration issue? + Locales addition

### ISSUE THREAD

**Issue by sirweezle** [radiant-gaming-public/rad_gsr#1]
Locales needs to have a line added for the Police Menu to reference. Just add the following lines to your Locale file. 

  --GSR Test
  ['GSR Test'] = 'GSR Test',

Honestly not even sure if this would be an issue, but the syntax referenced in the README didn't match up with the rest. I changed it to match the rest of my client.lua file. 

{label = _U('GSR Test'),		value = 'gsr_test'}

**Comment by BattleRattt** [comment]
Would not make much of a difference but for the sake of allowing others to easily translate it, I have updated the files.

Thanks!
